//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTrackingMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sales
    {
        public int sal_id { get; set; }
        public Nullable<int> sal_prd_id { get; set; }
        public Nullable<int> sal_stf_id { get; set; }
        public Nullable<int> sal_ctm_id { get; set; }
        public Nullable<decimal> sal_salePrice { get; set; }
        public Nullable<System.DateTime> sal_date { get; set; }
    
        public virtual tbl_customers tbl_customers { get; set; }
        public virtual tbl_products tbl_products { get; set; }
        public virtual tbl_staff tbl_staff { get; set; }
    }
}
