//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTrackingMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_admins
    {
        public int adm_id { get; set; }
        public string adm_username { get; set; }
        public string adm_password { get; set; }
        public Nullable<bool> adm_status { get; set; }
    }
}
