//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTrackingMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_products()
        {
            this.tbl_sales = new HashSet<tbl_sales>();
        }
    
        public int prd_id { get; set; }
        public string prd_name { get; set; }
        public string prd_brand { get; set; }
        public Nullable<short> prd_stock { get; set; }
        public Nullable<decimal> prd_purchasePrice { get; set; }
        public Nullable<decimal> prd_salePrice { get; set; }
        public Nullable<int> prd_ctg_id { get; set; }
        public Nullable<bool> prd_status { get; set; }
    
        public virtual tbl_categories tbl_categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_sales> tbl_sales { get; set; }
    }
}
